project:
  type: website
  

website:
  favicon: "Favicon.png"
  title: "Stat Devs"
  navbar:
    title: false
    pinned: true
    logo: "Navbar.png" 
    background: "#1d4355"
    left:
      - href: index.qmd
        text: "Home"
      - consulting.qmd
      - training.qmd
      - portfolio.qmd
      - blog.qmd
      - about.qmd
    right: 
      
      - href: https://twitter.com/DevsStat
        icon: twitter
      - href:  https://www.linkedin.com/company/stat-devs
        icon: linkedin
      - href: https://github.com/Stat-Devs
        icon: github
  search: false
      
      

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false

editor: visual

