project:
  type: website
  output-dir: docs
  

website:
  favicon: "Favicon.png"
  title: "Stat Devs"
  google-analytics: "G-K3TBBS59PL"
  navbar:
    title: false
    pinned: true
    logo: "Navbar.png" 
    background: "white"
    right:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - consulting.qmd
      - training.qmd
      - portfolio.qmd
      - blog.qmd
      - exploratory-sunday.qmd
      
      - href: index.qmd#cont
        text: "Contact Us"
      - href: https://twitter.com/StatDevs 
        icon: twitter
      - href: https://www.linkedin.com/company/stat-devs
        icon: linkedin
      - href: https://github.com/Stat-Devs
        icon: github
      - href: https://www.facebook.com/profile.php?id=100088076201356
        icon: facebook
  search: false
      
      

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false

editor: visual

