project:
  type: website

website:
  title: "Stat Devs"
  navbar:
    logo: "Final-Logo.png"     
    background: "#6c9286"
    left:
      - href: index.qmd
        text: "Home"
      - portfolio.qmd
      - blog.qmd
      - about.qmd
        
     
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

